language: ruby
rvm:
  - 2.2.4

script: bundle exec lyp test . --env --install

cache:
  bundler: true
  directories:
    - $HOME/.lyp
    
env:
  - LILYPOND_VERSION=2.18.2
  - LILYPOND_VERSION=2.19.35
